### ISSUE TITLE
Ordering of tests

### ISSUE THREAD

**Issue by leesus** [tomaszpolanski/fast_flutter_driver#91]
Is there any way to order the tests run in `generic_test.dart` short of hackily naming them with number prefixes or similar?

I tried hardcoding a `generic_test.dart` file, but it's overwritten when calling `fastdriver`.

The specific use case is ensuring login tests come first, and logout tests last, to prevent having to login in each test suite, and then I can just restart the app in the intermediary suites and maintain logged in state.

**Comment by tomaszpolanski** [comment]
Hey @leesus,
currently, it's not possible to do that. 
In your project, you show the login screen when the user does not have an access token, right?
When a user logged in in the previous session, you detect during the startup that the login screen is not displayed and then you show the logged-in experience, right?

**Solution 1**
In my project, when I do not want to test login flow, I just inject access token (via `TestConfiguration`) to be used for the user. 
This way is cleaner as you do not depend on the order of tests. Additionally, if your login tests fail in, then everything else fails as well.

**Solution 2**
This one is messy but will work. Now I am sorting the tests by name. So in the root of your tests (eg in `test_driver`) folder, put your login tests in a folder like `_login_tests` and because `_` character should be coming before your other folders/test files, it will be called first

This will be available in `1.3.3`
